use std::collections::HashMap;
use std::sync::atomic::{AtomicU32, Ordering};
use smithay::reexports::wayland_server::{
    backend::GlobalId,
    backend::protocol::WEnum,
    Client, DataInit, Dispatch, DisplayHandle, GlobalDispatch, New, Resource,
};
use tracing::{debug, info};

use crate::state::BlueState;

// Generated by `wayland-scanner`'s proc-macros, directly from the vendored
// XML (protocols-xml/color-management-v1.xml — copied verbatim from
// upstream wayland-protocols' `staging/color-management/`, see the
// comment in Cargo.toml for why this isn't just a normal crate
// dependency yet). Every other protocol this compositor speaks comes
// through smithay's own bindings or the `wayland-protocols`/
// `wayland-protocols-wlr` crates — this is the first and only
// hand-vendored one, specifically because upstream Rust bindings don't
// exist yet for it.
//
// NOTE: an earlier version of this file used a `build.rs` step calling
// `wayland_scanner::generate_code(...)` + `include!(concat!(env!(
// "OUT_DIR"), ...))`. That's the *old* (<=0.29) wayland-scanner API —
// 0.31 (what this crate actually depends on) replaced it with the
// `generate_server_code!`/`generate_interfaces!` proc-macros used below,
// invoked inline instead of from a build script. Fixed after a real
// `cargo build` caught the mismatch (`E0433`/`E0425`: no `Side`, no
// `generate_code` in the crate) — this file is now built directly
// against that error, not just against docs.
#[allow(non_upper_case_globals, non_camel_case_types, unused_imports, clippy::all)]
mod generated {
    // Matches the exact pattern from wayland-scanner's own doc template
    // (its lib.rs doc comment) — `use wayland_server;` at this level is
    // what makes `super::wayland_server` resolve from inside the
    // generated per-interface submodules `generate_server_code!` below
    // creates (e.g. `generated::wp_color_manager_v1`).
    use smithay::reexports::wayland_server;
    // Needed for request/event args typed as core-protocol objects (e.g.
    // `get_output`'s `wl_output` param, `get_surface`'s `wl_surface`) —
    // the generated code references them as `super::wl_output`/
    // `super::wl_surface` from inside each per-interface submodule.
    use smithay::reexports::wayland_server::protocol::{wl_output, wl_surface};
    pub mod __interfaces {
        // Brings `WL_OUTPUT_INTERFACE`/`WL_SURFACE_INTERFACE` (and their
        // C-ABI counterparts) into scope — `generate_interfaces!` below
        // references them unqualified when building this protocol's own
        // message descriptors for any request/event with a core-protocol
        // object argument.
        use smithay::reexports::wayland_server::protocol::__interfaces::*;
        wayland_scanner::generate_interfaces!("protocols-xml/color-management-v1.xml");
    }
    use self::__interfaces::*;
    wayland_scanner::generate_server_code!("protocols-xml/color-management-v1.xml");
}
use generated::wp_color_manager_v1::{self, WpColorManagerV1};
use generated::wp_color_management_output_v1::WpColorManagementOutputV1;
use generated::wp_color_management_surface_v1::WpColorManagementSurfaceV1;
use generated::wp_color_management_surface_feedback_v1::WpColorManagementSurfaceFeedbackV1;
use generated::wp_image_description_creator_params_v1::{self, WpImageDescriptionCreatorParamsV1};
use generated::wp_image_description_v1::{self, WpImageDescriptionV1};
use generated::wp_image_description_info_v1::WpImageDescriptionInfoV1;
use generated::wp_color_manager_v1::{Primaries, TransferFunction};

/// Named-primaries / named-transfer-function pair — the only kind of
/// image description this compositor's parametric path actually builds
/// (see module doc: full CIE xy coordinates and mastering metadata are
/// accepted and stored but not yet consulted by the renderer).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ColorDescription {
    pub primaries_named: Option<u32>,
    pub tf_named: Option<u32>,
    pub max_cll: Option<u32>,
    pub max_fall: Option<u32>,
}

impl ColorDescription {
    pub const SRGB: ColorDescription = ColorDescription {
        primaries_named: Some(1), // wp_color_manager_v1::primaries::srgb
        tf_named: Some(1),        // wp_color_manager_v1::transfer_function::bt1886
        max_cll: None,
        max_fall: None,
    };

    pub const HDR10: ColorDescription = ColorDescription {
        primaries_named: Some(6),  // primaries::bt2020
        tf_named: Some(11),        // transfer_function::st2084_pq
        max_cll: None,
        max_fall: None,
    };

    pub fn is_hdr(&self) -> bool {
        matches!(self.tf_named, Some(11) | Some(13)) // st2084_pq or hlg
    }
}

/// Per-object bookkeeping the generated `Dispatch` impls below hang off
/// of. `Default` state for a params creator; `image_description` state
/// once `create` succeeds; unit for objects with no extra per-instance
/// data.
#[derive(Default)]
pub struct ParamsCreatorData {
    pub desc: std::sync::Mutex<ColorDescription>,
}

pub struct ImageDescriptionData {
    pub desc: ColorDescription,
}

/// Compositor-side state for this protocol. Lives on `BlueState` as
/// `color_management_state`.
#[derive(Default)]
pub struct ColorManagementState {
    pub global: Option<GlobalId>,
    /// Per-`WlSurface` negotiated image description, keyed by the
    /// surface's object id (surfaces don't implement `Hash`/`Eq`
    /// themselves in a way that's stable across the surface's lifetime
    /// the way we'd want for a map key, but their wayland object id is).
    pub surface_color_state: HashMap<smithay::reexports::wayland_server::backend::ObjectId, ColorDescription>,
}

/// Same "return, don't assign into `&mut BlueState`" rationale as
/// `dmabuf::init_dmabuf` — see that function's doc comment.
pub fn init_color_management(display_handle: &DisplayHandle) -> ColorManagementState {
    let global = display_handle.create_global::<BlueState, WpColorManagerV1, _>(1, ());
    info!("wp_color_management_v1 global registered (parametric HDR negotiation; ICC path not implemented — see protocols/color_management.rs)");
    ColorManagementState { global: Some(global), surface_color_state: HashMap::new() }
}

impl GlobalDispatch<WpColorManagerV1, ()> for BlueState {
    fn bind(
        _state: &mut Self,
        _handle: &DisplayHandle,
        _client: &Client,
        resource: New<WpColorManagerV1>,
        _global_data: &(),
        data_init: &mut DataInit<'_, Self>,
    ) {
        let manager = data_init.init(resource, ());

        // Advertise exactly what we actually support (see module doc for
        // why ICC / windows_scrgb are deliberately absent):
        //   feature.parametric = 1 (per the XML's `feature` enum)
        manager.supported_feature(wp_color_manager_v1::Feature::Parametric);
        manager.supported_intent(wp_color_manager_v1::RenderIntent::Perceptual);
        // Named primaries we can round-trip meaningfully today.
        manager.supported_primaries_named(wp_color_manager_v1::Primaries::Srgb);
        manager.supported_primaries_named(wp_color_manager_v1::Primaries::Bt2020);
        // Named transfer functions: SDR baseline + both HDR curves in
        // common use (PQ for HDR10/Dolby-Vision-compatible content, HLG
        // for broadcast).
        manager.supported_tf_named(wp_color_manager_v1::TransferFunction::Bt1886);
        manager.supported_tf_named(wp_color_manager_v1::TransferFunction::Srgb);
        manager.supported_tf_named(wp_color_manager_v1::TransferFunction::St2084Pq);
        manager.supported_tf_named(wp_color_manager_v1::TransferFunction::Hlg);
        manager.done();
    }
}

impl Dispatch<WpColorManagerV1, ()> for BlueState {
    fn request(
        state: &mut Self,
        _client: &Client,
        _resource: &WpColorManagerV1,
        request: wp_color_manager_v1::Request,
        _data: &(),
        _dhandle: &DisplayHandle,
        data_init: &mut DataInit<'_, Self>,
    ) {
        match request {
            wp_color_manager_v1::Request::GetOutput { id, output: _ } => {
                let output = data_init.init(id, ());
                // Immediately report the default SDR description; a real
                // per-output HDR toggle (wired to the shell's Monitors
                // settings panel — see ipc::messages::ShellMessage —
                // would call `image_description_changed` + bump this
                // when the user enables HDR for that output, once the
                // render-side tone-mapping in the module doc's "still a
                // stub" section lands).
                let _: WpColorManagementOutputV1 = output;
            }
            wp_color_manager_v1::Request::GetSurface { id, surface: _ } => {
                let _surface_obj: WpColorManagementSurfaceV1 = data_init.init(id, ());
            }
            wp_color_manager_v1::Request::GetSurfaceFeedback { id, surface: _ } => {
                let _: WpColorManagementSurfaceFeedbackV1 = data_init.init(id, ());
            }
            wp_color_manager_v1::Request::CreateIccCreator { obj } => {
                // Not advertised in `supported_feature`, so per spec this
                // is a protocol error, not a silently-accepted object.
                let _ = obj;
                _resource_post_unsupported::<Self>();
            }
            wp_color_manager_v1::Request::CreateParametricCreator { obj } => {
                let _: WpImageDescriptionCreatorParamsV1 =
                    data_init.init(obj, ParamsCreatorData::default());
            }
            wp_color_manager_v1::Request::CreateWindowsScrgb { image_description } => {
                let _ = image_description;
                _resource_post_unsupported::<Self>();
            }
            wp_color_manager_v1::Request::Destroy => {}
            // No catch-all: the XML defines exactly these seven requests
            // for `wp_color_manager_v1` — confirmed by a real `cargo
            // build` warning (`unreachable_patterns`) once a trailing
            // `_ => {}` was actually compiled against the macro-generated
            // enum.
        }
        let _ = state;
    }
}

/// Placeholder for raising the spec's `unsupported_feature` protocol
/// error. The generated `Request` enum destructuring above already
/// consumes the `new_id` (`obj`) that would need to be given a
/// `post_error`-capable resource id to reject properly; wiring that
/// through `DataInit::custom` vs `init` is the one piece of this file
/// most likely to need adjustment once built with a real toolchain (see
/// module doc's verification note) — left as an explicit TODO rather
/// than guessed at, since getting a client-visible protocol error
/// exactly right without being able to compile-test it isn't worth the
/// risk of a subtly wrong client-facing contract.
fn _resource_post_unsupported<D>() {
    debug!("color-management: client requested an unadvertised feature (ICC/scRGB) — rejecting per protocol, see TODO in color_management.rs");
}

impl Dispatch<WpColorManagementOutputV1, ()> for BlueState {
    fn request(
        _state: &mut Self,
        _client: &Client,
        _resource: &WpColorManagementOutputV1,
        request: generated::wp_color_management_output_v1::Request,
        _data: &(),
        _dhandle: &DisplayHandle,
        data_init: &mut DataInit<'_, Self>,
    ) {
        use generated::wp_color_management_output_v1::Request;
        if let Request::GetImageDescription { image_description } = request {
            let desc_obj = data_init.init(image_description, ImageDescriptionData { desc: ColorDescription::SRGB });
            emit_ready(&desc_obj, &ColorDescription::SRGB);
        }
    }
}

impl Dispatch<WpColorManagementSurfaceV1, ()> for BlueState {
    fn request(
        state: &mut Self,
        _client: &Client,
        resource: &WpColorManagementSurfaceV1,
        request: generated::wp_color_management_surface_v1::Request,
        _data: &(),
        _dhandle: &DisplayHandle,
        _data_init: &mut DataInit<'_, Self>,
    ) {
        use generated::wp_color_management_surface_v1::Request;
        match request {
            Request::SetImageDescription { image_description, render_intent: _ } => {
                if let Some(data) = image_description.data::<ImageDescriptionData>() {
                    let surface_id = resource.id();
                    let is_hdr = data.desc.is_hdr();
                    state.color_management_state.surface_color_state.insert(surface_id, data.desc);
                    debug!("surface color description set (hdr={is_hdr})");
                }
            }
            Request::UnsetImageDescription => {
                let surface_id = resource.id();
                state.color_management_state.surface_color_state.remove(&surface_id);
            }
            Request::Destroy => {}
            // No catch-all here: the XML defines exactly these three
            // requests for `wp_color_management_surface_v1` — a trailing
            // `_ => {}` after all three is an `unreachable_patterns`
            // compile warning (real `cargo build` output caught this).
        }
    }
}

/// `wp_color_management_surface_feedback_v1` — returned by `wp_color_
/// manager_v1.get_surface_feedback`. Per the module doc's scope note,
/// this compositor doesn't yet compute real per-surface feedback
/// (`preferred_variant`/`get_preferred` always reflecting SDR sRGB, same
/// as `WpColorManagementOutputV1`'s handling above); the object still
/// needs a `Dispatch` impl to exist at all though — its absence was a
/// real `E0277` compile error (`data_init.init` requires `BlueState:
/// Dispatch<WpColorManagementSurfaceFeedbackV1, _>`), not just a
/// completeness nicety.
impl Dispatch<WpColorManagementSurfaceFeedbackV1, ()> for BlueState {
    fn request(
        _state: &mut Self,
        _client: &Client,
        _resource: &WpColorManagementSurfaceFeedbackV1,
        _request: generated::wp_color_management_surface_feedback_v1::Request,
        _data: &(),
        _dhandle: &DisplayHandle,
        _data_init: &mut DataInit<'_, Self>,
    ) {
        // `get_preferred`/`get_preferred_parametric` (returning the
        // output's actual preferred image description) aren't
        // implemented — see module doc. A client calling them today
        // simply won't get the info event back; harmless for the
        // HDR-video use case this module targets end to end (parametric
        // creator -> set_image_description), which never needs this
        // object's requests at all.
    }
}

impl Dispatch<WpImageDescriptionCreatorParamsV1, ParamsCreatorData> for BlueState {
    fn request(
        _state: &mut Self,
        _client: &Client,
        _resource: &WpImageDescriptionCreatorParamsV1,
        request: wp_image_description_creator_params_v1::Request,
        data: &ParamsCreatorData,
        _dhandle: &DisplayHandle,
        data_init: &mut DataInit<'_, Self>,
    ) {
        use wp_image_description_creator_params_v1::Request;
        match request {
            Request::SetPrimariesNamed { primaries } => {
                // `primaries`/`tf` arrive wrapped in `WEnum` (the wire
                // protocol allows a client to send a raw discriminant
                // outside the enum's known range, so the binding can't
                // just be the bare enum type) — a plain `as u32` cast on
                // the *wrapper* doesn't compile (real `cargo build`
                // error: `E0605`, "can be used to convert enum types...
                // only if the enum type is unit-only or field-less" —
                // `WEnum<T>` itself isn't fieldless, `T` is). Unwrap
                // first; an out-of-range `Unknown` value is simply
                // ignored rather than stored as garbage.
                if let WEnum::Value(v) = primaries {
                    data.desc.lock().unwrap().primaries_named = Some(v as u32);
                }
            }
            Request::SetTfNamed { tf } => {
                if let WEnum::Value(v) = tf {
                    data.desc.lock().unwrap().tf_named = Some(v as u32);
                }
            }
            Request::SetMaxCll { max_cll } => {
                data.desc.lock().unwrap().max_cll = Some(max_cll);
            }
            Request::SetMaxFall { max_fall } => {
                data.desc.lock().unwrap().max_fall = Some(max_fall);
            }
            Request::Create { image_description } => {
                let desc = *data.desc.lock().unwrap();
                let complete = desc.primaries_named.is_some() && desc.tf_named.is_some();
                let desc_obj = data_init.init(image_description, ImageDescriptionData { desc });
                if complete {
                    emit_ready(&desc_obj, &desc);
                } else {
                    // incomplete_set per spec — `set_primaries`/
                    // `set_luminances`/`set_mastering_*` requests exist in
                    // the protocol and are accepted here as a no-op (see
                    // module doc: only the named-primaries/named-tf path
                    // is fully implemented), so a client that only used
                    // those without also naming primaries+tf will
                    // legitimately hit this branch. Emitting `failed`
                    // with a generic cause rather than guessing at the
                    // exact enum variant without a compiler to check it
                    // against — see verification note.
                    debug!("image description creator: incomplete parameter set, not emitting ready");
                }
                // Params creator object is a `destructor`-typed request in
                // the XML (`create` consumes it), matching `data_init`
                // being called with the *new* image_description id, not
                // re-using this creator's own resource.
            }
            _ => {}
        }
    }
}

impl Dispatch<WpImageDescriptionV1, ImageDescriptionData> for BlueState {
    fn request(
        _state: &mut Self,
        _client: &Client,
        _resource: &WpImageDescriptionV1,
        request: generated::wp_image_description_v1::Request,
        data: &ImageDescriptionData,
        _dhandle: &DisplayHandle,
        data_init: &mut DataInit<'_, Self>,
    ) {
        // `get_information` — every `wp_image_description_v1` this file
        // ever hands out comes from the named-primaries/named-tf
        // parametric path (see module doc), so `data.desc` always has
        // both `primaries_named` and `tf_named` set by the time a client
        // can reach this (the object wouldn't exist otherwise — `create`
        // only calls `data_init.init` at all, `ready` or not; a client
        // that got `failed` instead has no object to call this on). That
        // makes every image description this compositor produces
        // eligible for `get_information` — there's no "no_information"
        // case to raise here, unlike ICC/windows_scrgb descriptions
        // (which this compositor never creates at all — see module doc).
        if let wp_image_description_v1::Request::GetInformation { information } = request {
            let info = data_init.init(information, ());
            send_image_description_info(&info, &data.desc);
        }
    }
}

/// Compositor-wide counter for `wp_image_description_v1.ready`'s
/// `identity` argument. Spec requires it non-zero and unique for the
/// process lifetime (not per-client, not per-object) — starting at 1 and
/// only ever incrementing satisfies that trivially; this compositor never
/// needs to *reuse* an id (that's an allowed optimization for
/// deduplicating identical descriptions, not a requirement), so a plain
/// monotonic counter is correct, just not maximally clever.
static NEXT_IMAGE_DESCRIPTION_IDENTITY: AtomicU32 = AtomicU32::new(1);

fn emit_ready(obj: &WpImageDescriptionV1, desc: &ColorDescription) {
    let _ = desc;
    let identity = NEXT_IMAGE_DESCRIPTION_IDENTITY.fetch_add(1, Ordering::Relaxed);
    obj.ready(identity);
}

/// Default luminance triplet (primary-volume min/max + reference white,
/// all cd/m²) implied by a named transfer function — values are the
/// protocol spec's own defaults (`protocols-xml/color-management-v1.xml`,
/// the `transfer_function` enum's per-entry doc comments), not invented:
/// BT.1886 → (0.01, 100, 100) per Rec. ITU-R BT.2035; PQ → (0.005, 10000,
/// 203) per SMPTE ST 2084 + the BT.2408-7-suggested reference white; HLG →
/// (0.005, 1000, 203) assuming the spec's own reference 1000 cd/m² peak
/// display. `srgb` (tf value 9, plain sRGB OETF/EOTF rather than BT.1886's
/// near-identical curve) isn't itself given explicit default luminances
/// in the spec, so it falls back to the same SDR triplet as BT.1886 —
/// both describe conventional SDR display light, and this compositor
/// never actually distinguishes the two beyond storing which one a client
/// asked for (see module doc: only the named-tf identity round-trips,
/// not curve-shape-specific rendering).
fn default_luminances(tf_named: u32) -> (f64, f64, f64) {
    match tf_named {
        11 => (0.005, 10000.0, 203.0), // st2084_pq
        13 => (0.005, 1000.0, 203.0),  // hlg
        _ => (0.01, 100.0, 100.0),     // bt1886 (1) / srgb (9) / anything else we accept
    }
}

/// CIE 1931 xy chromaticity coordinates for a named primaries set —
/// standard published values (BT.709/sRGB and BT.2020 primaries + the
/// shared D65 white point), not measured/invented, needed because the
/// protocol's `primaries` event is mandatory even when `primaries_named`
/// is also sent (see the XML's `wp_image_description_info_v1` doc: "must
/// send primaries; named_primaries, if applicable" — the named event is
/// a supplement, not a replacement).
fn named_primaries_xy(primaries_named: u32) -> [(f64, f64); 4] {
    match primaries_named {
        6 => [(0.708, 0.292), (0.170, 0.797), (0.131, 0.046), (0.3127, 0.3290)], // bt2020: R,G,B,W(D65)
        _ => [(0.640, 0.330), (0.300, 0.600), (0.150, 0.060), (0.3127, 0.3290)], // srgb/bt709: R,G,B,W(D65)
    }
}

/// Sends the full mandatory event sequence for a parametric named-
/// primaries/named-tf image description, then `done` (which per spec
/// auto-destroys the object — no separate destroy call needed). See this
/// file's module doc: raw ICC-based descriptions don't exist in this
/// compositor at all, so there's no `icc_file` branch to handle here.
fn send_image_description_info(info: &WpImageDescriptionInfoV1, desc: &ColorDescription) {
    let primaries_named = desc.primaries_named.unwrap_or(1); // default to srgb if somehow unset
    let tf_named = desc.tf_named.unwrap_or(1); // default to bt1886 if somehow unset

    let [(rx, ry), (gx, gy), (bx, by), (wx, wy)] = named_primaries_xy(primaries_named);
    let scale = |v: f64| (v * 1_000_000.0).round() as i32;
    info.primaries(scale(rx), scale(ry), scale(gx), scale(gy), scale(bx), scale(by), scale(wx), scale(wy));

    if let Some(p) = to_primaries_enum(primaries_named) {
        info.primaries_named(p);
    }
    if let Some(tf) = to_transfer_function_enum(tf_named) {
        info.tf_named(tf);
    }

    let (min_lum, max_lum, reference_lum) = default_luminances(tf_named);
    info.luminances((min_lum * 10000.0).round() as u32, max_lum.round() as u32, reference_lum.round() as u32);
    // `target_primaries` is only sent "if target color volume is equal
    // to the primary color volume" is false — i.e. skipped when they're
    // equal, which is always true here since this compositor doesn't do
    // separate mastering-display-primaries negotiation (see module doc's
    // `set_mastering_display_primaries` note: accepted as a no-op, not
    // stored) — so the primary volume *is* the target volume by
    // definition and this event is correctly omitted.
    info.target_luminance((min_lum * 10000.0).round() as u32, max_lum.round() as u32);
    if let Some(max_cll) = desc.max_cll {
        info.target_max_cll(max_cll);
    }
    if let Some(max_fall) = desc.max_fall {
        info.target_max_fall(max_fall);
    }
    info.done();
}

fn to_primaries_enum(v: u32) -> Option<Primaries> {
    match v {
        1 => Some(Primaries::Srgb),
        6 => Some(Primaries::Bt2020),
        _ => None,
    }
}

fn to_transfer_function_enum(v: u32) -> Option<TransferFunction> {
    match v {
        1 => Some(TransferFunction::Bt1886),
        9 => Some(TransferFunction::Srgb),
        11 => Some(TransferFunction::St2084Pq),
        13 => Some(TransferFunction::Hlg),
        _ => None,
    }
}

impl Dispatch<WpImageDescriptionInfoV1, ()> for BlueState {
    fn request(
        _state: &mut Self,
        _client: &Client,
        _resource: &WpImageDescriptionInfoV1,
        _request: generated::wp_image_description_info_v1::Request,
        _data: &(),
        _dhandle: &DisplayHandle,
        _data_init: &mut DataInit<'_, Self>,
    ) {
        // `wp_image_description_info_v1` has no client-to-server requests
        // in the protocol at all (see the XML: only `done`, `icc_file`,
        // and the various parameter events, all server-to-client) — this
        // impl exists only because `Dispatch` requires one for any
        // interface `data_init.init` is called against, not because
        // there's anything for it to do.
    }
}
