pub mod compositor;
pub mod data_device;
pub mod decoration;
pub mod extra_protocols;
pub mod layer_shell;
pub mod output;
pub mod seat;
pub mod tablet;
pub mod xdg_shell;
#[cfg(feature = "xwayland")]
pub mod xwayland_shell;
